[root]
name = "root"
description = "This is the root python file"
filename = "main.py"

[[root.packages]]
name = "sample"

[[root.packages.modules]]
name = "display"
description = "This is the display module"

[[root.packages.modules.classes]]
name = "animal"
description = "This is the animal class"

[[root.packages.modules.functions]]
name = "display"
parameters = ["msg"]
description = "this is the display function"

[[root.packages]]
name = "tests"

[[root.packages.modules]]
name = "api"
description = "This is the api module"

[[root.packages.modules.functions]]
name = "create_api"
parameters = ["id", "new"]
description = "This is the create api function"
